<?php

namespace common\models;

use backend\utils\D;
use Yii;
use yii\helpers\ArrayHelper;
use yii\helpers\BaseUrl;

/**
 * This is the model class for table "base_station".
 *
 * @property int $id id
 * @property string $articul артикул
 * @property string $name Наименование
 * @property int $measure ед.изм.
 * @property int $count кол-во
 * @property int $price Цена
 * @property int $cost Стоимость
 * @property string $mark Марка
 * @property double $performance Производительность
 * @property int $people Кол-во человек
 * @property int $fecal_nas Фекал. нас.
 * @property int $sp с\п
 * @property int $deep Глубина трубы
 * @property int $type_calculate_id Используется для расчетов
 * @property int $self_cost Себестоимость
 * @property int $montaj Монтаж
 * @property int $pnr ПНР
 * @property int $rshm РШМ
 * @property int $yakor Якорение
 * @property string $length Длина
 * @property string $width Ширина
 * @property string $height Высота
 * @property int $utepl Утеплитель
 * @property string $water Вода
 * @property string $sand_manual В ручную
 * @property string $sand_tech Техника
 * @property string $cement_manual цемент в ручную
 * @property int $cement_manual_pac
 * @property string $cement_tech цемент техника
 * @property int $cement_tech_pac
 * @property string $pit_manual Котлован в ручную
 * @property string $pit_tech Котлован техника
 * @property int $gasket Прокладка тр.
 * @property string $with_chasers Ширина грунтозацепов
 */
class BaseStation extends \yii\db\ActiveRecord
{

    public static function getAvailableForCurrent()
    {
        $region_id = Yii::$app->user->identity->region_id;
        return BaseStation::find()->joinWith('prices as prices')->where(['prices.is_available' => 1])->andWhere(['prices.region_id' => $region_id])->orderBy('id')->all();
    }

    public
    function setPrices($prices)
    {


        if ($prices) {
            $Deleted_prices = StationPrices::deleteAll(['station_id' => $this->id]);
            Yii::$app->session->setFlash('danger', " COUNT Deleted_schedules WAS DELETED " . $Deleted_prices);
            foreach ($prices as $price) {
                $stationPrice = new StationPrices();
                $stationPrice->price = $price['price'];
                $stationPrice->self_cost = $price['self_cost'];
                $stationPrice->cost = $price['cost'];
                $stationPrice->is_available = $price['is_available'];
                $stationPrice->region_id = $price['region_id'];
                $stationPrice->station_id = $this->id;
                if (!$stationPrice->save()) D::dump($stationPrice->errors);
            }


        }

    }

    public function beforeDelete()
    {
        StationPrices::deleteAll(['station_id' => $this->id]);
        return parent::beforeDelete(); // TODO: Change the autogenerated stub
    }

    public function afterSave($insert, $changedAttributes)
    {

        /* @var $station BaseStation */
        /* @var $region Regions */

        if ($this->isNewRecord) {
            $queryRegions = Regions::find()->where(['id' => 4]);
            D::success(" COUNT REGIONS = " . $queryRegions->count());
            $regions = $queryRegions->all();
            foreach ($regions as $region) {
                D::primary(" REGION NAME = " . $region->name);
                $region->generatePrices($this->id);
            }
        }

        parent::afterSave($insert, $changedAttributes); // TODO: Change the autogenerated stub
    }


    public function getPrices()
    {
        return $this->hasMany(StationPrices::className(), ['station_id' => 'id']);
    }

    public function getRegionPrice($region_id = 0)
    {
        if (!$region_id) $region_id = Yii::$app->user->identity->region_id;
        return $this->hasOne(StationPrices::className(), ['station_id' => 'id'])->andWhere(['region_id' => $region_id]);
    }

    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return 'base_station';
    }

    public function debugSave()
    {
        if (!$this->save()) {
            $keys = array_keys($this->getErrors());
            foreach ($keys as $key) {
                D::alert($key . "=" . $this->$key);
            }
            D::dump($this->getErrors());
        }
        // $this->save();
    }

    public function getMaterials()
    {
        return $this->hasMany(MaterialToStation::className(), ['station_id' => 'id']);
    }


    public function mapMeasure()
    {
        return [
            0 => 'шт.',
        ];
    }

    public function mapCalculateType()
    {
        return ArrayHelper::map(BaseStationCalculateType::find()->all(), 'id', 'name');
    }

    public function mapGroups()
    {
        return ArrayHelper::map(BaseStationGroup::find()->all(), 'group_id', 'name');
    }

    public function getCalculateType()
    {
        return $this->hasOne(BaseStationCalculateType::className(), ['id' => 'type_calculate_id']);
    }

    public function getGroups()
    {
        return $this->hasMany(BaseStationGroup::className(), ['group_id' => 'group_id'])
            ->viaTable(BaseStationToGroup::tableName(), ['station_id' => 'id']);
    }


    public function getGroupsId()
    {
        return $this->hasMany(BaseStationToGroup::className(), ['station_id' => 'id']);
    }

    public function mapFecalnas()
    {
        return [
            0 => '',
            1 => 'Н',
        ];
    }

    public function mapSp()
    {
        return [
            1 => 'С',
            2 => 'П',
        ];
    }

    public static function numericProperties()
    {
        return ['performance', 'length', 'width', 'height', 'water', 'sand_manual', 'sand_tech', 'cement_manual', 'cement_tech', 'pit_manual', 'pit_tech'];

    }

    public function getRprice()
    {
        return $this->regionPrice->price;
    }

    public function getRcost()
    {
        return $this->regionPrice->cost;
    }

    public function getRself_cost()
    {
        return $this->regionPrice->self_cost;
    }

    public static function integerProperties()
    {
        return ['measure', 'count', 'price', 'cost', 'people', 'fecal_nas', 'sp', 'deep', 'type_calculate_id', 'self_cost', 'montaj', 'pnr', 'rshm', 'yakor', 'utepl', 'cement_manual_pac', 'cement_tech_pac', 'gasket'];

    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['measure', 'count', 'price', 'cost', 'people', 'fecal_nas', 'sp', 'deep', 'type_calculate_id', 'self_cost', 'montaj', 'pnr', 'rshm', 'yakor', 'utepl', 'cement_manual_pac', 'cement_tech_pac', 'gasket'], 'integer'],
            [['performance', 'length', 'width', 'height', 'water', 'sand_manual', 'sand_tech', 'cement_manual', 'cement_tech', 'pit_manual', 'pit_tech'], 'number'],
            [['articul'], 'string', 'max' => 50],
            [['name', 'mark'], 'string', 'max' => 256],
            [['with_chasers'], 'string', 'max' => 10],
        ];
    }


    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'id' => 'id',
            'articul' => 'артикул',
            'name' => 'Наименование',
            'measure' => 'ед.изм.',
            'count' => 'кол-во',
            'price' => 'Цена',
            'rprice' => 'Региональная Цена',
            'cost' => 'Стоимость',
            'rcost' => 'Рег.Стоимость',
            'mark' => 'Марка',
            'performance' => 'Производ.',
            'people' => 'Кол-во человек',
            'fecal_nas' => 'Фекал. нас.',
            'sp' => 'с\\п',
            'deep' => 'Глубина трубы',
            'type_calculate_id' => 'Используется для расчетов',
            'self_cost' => 'Себестоимость',
            'rself_cost' => 'Рег. Себестоимость',
            'montaj' => 'Монтаж',
            'pnr' => 'ПНР',
            'rshm' => 'РШМ',
            'yakor' => 'Якорение',
            'length' => 'Длина',
            'width' => 'Ширина',
            'height' => 'Высота',
            'utepl' => 'Утеплитель',
            'water' => 'Вода',
            'sand_manual' => 'В ручную',
            'sand_tech' => 'Техника',
            'cement_manual' => 'цемент в ручную',
            'cement_manual_pac' => 'Cement Manual Pac',
            'cement_tech' => 'цемент техника',
            'cement_tech_pac' => 'Cement Tech Pac',
            'pit_manual' => 'Котлован в ручную',
            'pit_tech' => 'Котлован техника',
            'gasket' => 'Прокладка тр.',
            'with_chasers' => 'Ширина грунтозацепов',
        ];
    }

    public function formulaLabels()
    {
        return [
            'id',
            'articul',
            'name',
            'rprice',
            'price',
            'rcost',
            'cost',
            'rprice',
            'rcost',
            'people',
            'fecal_nas',
            'sp',
            'deep',
            'type_calculate_id',
            'rself_cost',
            'self_cost',
            'montaj',
            'pnr',
            'rshm',
            'yakor',
            'length',
            'width',
            'height',
            'utepl',
            'water',
            'sand_manual',
            'sand_tech',
            'cement_manual',
            'cement_manual_pac',
            'cement_tech',
            'cement_tech_pac',
            'pit_manual',
            'pit_tech',
            'gasket',
            'with_chasers',
        ];
    }

}
