<?php

namespace common\models;

use backend\utils\D;
use Yii;
use yii\helpers\ArrayHelper;

/**
 * This is the model class for table "smeta".
 *
 * @property int $smeta_id id
 * @property int $estimate_id
 * @property int $parent_id
 * @property int $current_stage
 * @property int $date
 * @property string $name
 */
class Smeta extends \yii\db\ActiveRecord
{

    protected $variables;
    protected $variablesKeys;

    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return 'smeta';
    }

    public static function forTest()
    {
        return self::find()->where(['forTest' => 1])->one();
    }

    public function ReplaceValue($value)
    {
        if ($value) {
            $new_value = $value;
            if ($variables = $this->variables) {
                foreach ($variables as $key => $variable) {
                    $old_value = $new_value;
                    $new_value = preg_replace("/" . $key . "/", $this->getVariables()[$key], $old_value);
                 /*   if ($new_value != $old_value) {
                        if (in_array($key, ["G17", "G18"])) D::success($key . " " . $variable . " VALUE = " . $new_value);
                    }*/

                }
            }

        }
        return $new_value;


    }

    public function addVariables($variable)
    {
        $this->variables = array_merge($variable,$this->variables);
    }

    public function getVariables()
    {
        return $this->variables;
    }


    public function mapEstimates()
    {
        return ArrayHelper::map(Estimate::find()->all(), 'estimate_id', 'name');
    }

    public function beforeSave($insert)
    {

        return parent::beforeSave($insert);
    }

    public function getInputValues()
    {
        return $this->hasMany(InputValue::className(), ['smeta_id' => 'smeta_id']);
    }

    public function getEvents()
    {
        return $this->hasMany(SmetaEvents::className(), ['smeta_id' => 'smeta_id']);
    }

    public function beforeValidate()
    {

        if ($_POST) {
            $estimates = array_filter($_POST, function ($key) {
                return preg_match("/estimate_(\d{1,4})/", $key);
            }, ARRAY_FILTER_USE_KEY);
            $estimatesPlus = array_filter($estimates, function ($item) {
                return in_array($item, ['1', true, 1]);
            });
            if (!$estimatesPlus) {
                Yii::$app->session->setFlash('danger', 'Выберите смету');
                return false;
            }
            EstimatesToSmeta::updateAll(['status' => 0], ['smeta_id' => $this->smeta_id]);

            if ($estimates) {

                foreach ($estimates as $key => $estimate) {
                    preg_match("/estimate_(\d{1,4})/", $key, $matches);

                    if ($this->smeta_id) {
                        if ($existed = EstimatesToSmeta::find()->where(['smeta_id' => $this->smeta_id])->andWhere(['estimate_id' => $matches[1]])->one()) {
                            if ($existed->status != 1) {
                                $existed->status = 1;
                                $existed->save();

                            }
                        } else {

                            $new_estimateToSmeta = new EstimatesToSmeta(['smeta_id' => $this->smeta_id, 'estimate_id' => $matches[1], 'status' => 1]);

                            if (!$new_estimateToSmeta->save()) D::dump($new_estimateToSmeta->errors);
                        }

                    }
                }
            }
        }

        if (!$this->date) $this->date = time();
        if (!isset($this->user_id)) $this->user_id = Yii::$app->user->identity->getId();
        return parent::beforeValidate();
    }

    public function getEstimates()
    {
        return $this->hasMany(Estimate::className(), ['estimate_id' => 'estimate_id'])
            ->viaTable(EstimatesToSmeta::tableName(), ['smeta_id' => 'smeta_id']);
    }

    public function getEstimatesId()
    {
        return $this->hasMany(EstimatesToSmeta::className(), ['smeta_id' => 'smeta_id'])->select('estimate_id')->orderBy('priority')->andWhere(['status' => 1])->column();
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['date', 'user_id'], 'required'],
            [['estimate_id'], 'integer'],
            [['name'], 'string'],
            [['name'], 'safe'],
            [['date'], 'integer'],
        ];
    }

    public function afterSave($insert, $changedAttributes)
    {
        $this->generateVariables();
        parent::afterSave($insert, $changedAttributes); // TODO: Change the autogenerated stub
    }

    public function generateVariables()
    {

        if ($estimates = $this->estimates) {
            foreach ($estimates as $estimate) {
                D::success(" ESTIMATE NAME = " . $estimate->name);
                if ($events = $estimate->events) {
                    foreach ($events as $event) {
                        // D::success(" EVENT NAME = " . $event->name);
                        if ($smeta_event = SmetaEvents::find()->where(['event_id' => $event->event_id])->andWhere(['smeta_id' => $this->smeta_id])->one()) {
                        } else {
                            $smetaEvent = new SmetaEvents(['smeta_id' => $this->smeta_id, 'event_id' => $event->event_id]);
                            $smetaEvent->value = 0;
                            if (!$smetaEvent->save()) D::dump($smetaEvent->errors);
                        }


                    }
                }

                if ($inputs = $estimate->inputs) {
                    foreach ($inputs as $input) {
                        D::success(" INPUT NAME = " . $input->name);
                        if ($inputValue = InputValue::find()->where(['input_id' => $input->input_id])->andWhere(['smeta_id' => $this->smeta_id])->one()) {

                            InputValue::updateAll(['type' => $input->type], ['AND', ['input_id' => $input->input_id], ['smeta_id' => $this->smeta_id]]);
                        } else {
                            $inputValue = new InputValue(['smeta_id' => $this->smeta_id, 'type' => $input->type, 'input_id' => $input->input_id, 'estimate_id' => $estimate->estimate_id]);
                            if (!$inputValue->save()) D::dump($inputValue->errors);
                        }


                    }
                }
            }
        }

    }

    public function getUser()
    {
        return $this->hasOne(User::className(), ['id' => 'user_id']);
    }

    public function getStagesId()
    {
        return EstimateStage::find()->where(['status' => EstimateStage::STATUS_ACTIVE])->andWhere(['estimate_id' => $this->estimatesId])->select('stage_id')->column();
    }

    public function getOutputsId()
    {


        /* @var $stage     EstimateStage */
        /* @var $estimate     Estimate */
        $stages_id = [];
        if ($estimates = $this->estimates) {
            foreach ($estimates as $estimate) {

                if ($stages_ids_estimate = $estimate->getStagesOutput()->select('stage_id')->column()) {

                    $stages_id = array_merge($stages_id, $stages_ids_estimate);

                };
            }
            $outputs_ids = Output::find()->where(['in', 'stage_id', $stages_id])->select('output_id')->column();
            return $outputs_ids;
        };
    }

    public function getEstimate()
    {
        return $this->hasOne(Estimate::className(), ['estimate_id' => 'estimate_id']);
    }

    public function getBodyMaterials()
    {
        $body = '';
        if ($outputs = Output::find()->where(['in', 'output_id', $this->getOutputsId()])
            ->andWhere([
                'OR',
                ['like', 'formula', 'material_'],
                ['like', 'result', 'material_'],
            ])->select('output_id,name,formula,result')->all()) {
            foreach ($outputs as $output) {
                $body .= " " . $output->formula;
                $body .= " " . $output->result;
            }


        }
        if ($table_cells = TableCells::find()->where(['like', 'value', 'material_'])->select('value')->column()) {
            foreach ($table_cells as $table_cell) {
                $body .= " " . $table_cell;
            }


        }
        return $body;
    }

    public function getBodyWorks()
    {
        $body = '';
        if ($outputs = Output::find()->where(['in', 'output_id', $this->getOutputsId()])
            ->andWhere([
                'OR',
                ['like', 'formula', 'work_'],
                ['like', 'result', 'work_'],
            ])->select('output_id,name,formula,result')->all()) {
            foreach ($outputs as $output) {
                $body .= " " . $output->formula;
                $body .= " " . $output->result;
            }


        }
        if ($table_cells = TableCells::find()->where(['like', 'value', 'work_'])->select('value')->column()) {
            foreach ($table_cells as $table_cell) {
                $body .= " " . $table_cell;
            }


        }
        return $body;
    }

    public function loadVariables($params = [])
    {
        if (!$params['materials_id']) $params['materials_id'] = Material::preg_match($this->getBodyMaterials());
        if (!$params['works_id']) $params['works_id'] = Works::preg_match($this->getBodyWorks());
        $variables = array_merge($this->loadEvents(), $this->loadInputs(), $this->loadOutputs(),
            $this->loadStation(), $this->loadMaterials($params['materials_id']),
            $this->loadManager(), $this->loadCity(), $this->loadWorks($params['works_id']));

        $this->variables = $variables;
        $this->variablesKeys = array_keys($this->variables);


        return $variables;

    }


    public function loadInputs()
    {

        /* @var $inputValue InputValue */

        if ($inputValues = InputValue::find()->where(['smeta_id' => $this->smeta_id])->all()) {
            foreach ($inputValues as $inputValue) {

                if (in_array($inputValue->type, [2, 3, 4])) {
                    if (!$inputValue->value) $inputValue->value = 0;
                } else {
                    $inputValue->value = "'" . $inputValue->value . "'";
                }
                $variables["input_" . $inputValue->input_id . "_"] = $inputValue->value;

            }

            return $variables;

        } else return [];
    }

    public function loadOutputs()
    {

        /* @var $inputValue InputValue */

        if ($outputValues = OutputValue::find()->where(['smeta_id' => $this->smeta_id])->joinWith('output as output')->all()) {
            foreach ($outputValues as $outputValue) {

                if (in_array($outputValue->output->type, [2, 3, 4])) {
                    if (!$outputValue->value) $outputValue->value = 0;
                } else {
                    $outputValue->value = "'" . $outputValue->value . "'";
                }
                $variables["output_" . $outputValue->output_id . "_"] = $outputValue->value;

            }

            return $variables;

        } else return [];
    }

    public function getTraces()
    {
        return $this->hasMany(Tracing::className(), ['smeta_id' => 'smeta_id']);
    }


    public function loadEvents()
    {

        /* @var $event SmetaEvents */

        if ($events = SmetaEvents::find()->where(['smeta_id' => $this->smeta_id])->all()) {
            foreach ($events as $event) {
                $variables["event_" . $event->event_id . "_"] = $event->value;
            }

            return $variables;

        } else return [];
    }

    public function loadMaterials($materials_id = [])
    {

        /* @var $material Material */

        if ($materials = Material::find()->where(['in', 'id', $materials_id])->all()) {
            foreach ($materials as $material) {
                if ($params = Material::$formulaParams) {
                    foreach ($params as $param) {
                        $variables[$material->getFormulaName() . "." . $param] = $material->$param;
                    }
                }

            }

            return $variables;

        } else return [];
    }

    public function loadWorks($works_id = [])
    {

        /* @var $work Works */

        if ($works = Works::find()->where(['in', 'id', $works_id])->all()) {
            foreach ($works as $work) {
                if ($params = Works::$formulaParams) {
                    foreach ($params as $param) {
                        $variables[$work->getFormulaName() . "." . $param] = $work->$param;
                    }
                }

            }

            return $variables;

        } else return [];
    }

    public function loadStation()
    {
        $variables = [];

        /* @var $event SmetaEvents */

        if ($estimate_ids = $this->getEstimatesId()) {
            $active_stages = EstimateStage::find()->select('stage_id')->where(['in', 'estimate_id', $estimate_ids])->andWhere(['status' => EstimateStage::STATUS_ACTIVE])->column();
        };
        // D::dump($estimate_ids);
        if ($input = Input::find()->where(['in', 'stage_id', $active_stages])->andWhere(['type' => Input::IN_LIST_BASE_STATION])->one()) {
            //  D::dump($input->input_id);
            if ($inputValueStation = InputValue::find()->where(['input_id' => $input->input_id])->andWhere(['smeta_id' => $this->smeta_id])->one()) {
                $station_id = $inputValueStation->value;
                //   D::success($station_id);
            }
            if ($station = BaseStation::find()->where(['id' => $station_id])->asArray()->one()) {
                foreach ($station as $key => $value) {
                    if (!filter_var($value, FILTER_VALIDATE_FLOAT)) $value = "'" . $value . "'";
                    elseif (!$value) $value = 0;
                    $variables["station." . $key] = $value;
                }
            }
            if ($station) Yii::$app->session->set('station', $station);
            //   D::dump($station);

            return $variables;


        } else return [];
    }

    public function loadCity()
    {
        $variables = [];

        /* @var $event SmetaEvents */

        if ($estimate_ids = $this->getEstimatesId()) {
            $active_stages = EstimateStage::find()->select('stage_id')->where(['in', 'estimate_id', $estimate_ids])->andWhere(['status' => EstimateStage::STATUS_ACTIVE])->column();
        };
        // D::dump($estimate_ids);
        if ($input = Input::find()->where(['in', 'stage_id', $active_stages])->andWhere(['type' => Input::IN_LIST_OF_CITIES])->one()) {
            //  D::dump($input->input_id);
            if ($inputValueStation = InputValue::find()->where(['input_id' => $input->input_id])->andWhere(['smeta_id' => $this->smeta_id])->one()) {
                $station_id = $inputValueStation->value;
                //   D::success($station_id);
            }
            if ($station = City::find()->where(['id' => $station_id])->asArray()->one()) {
                foreach ($station as $key => $value) {
                    if (!filter_var($value, FILTER_VALIDATE_FLOAT)) $value = "'" . $value . "'";
                    elseif (!$value) $value = 0;
                    $variables["city." . $key] = $value;
                }
            } else return [];
            if ($station) Yii::$app->session->set('city', $station);
            //   D::dump($station);

            return $variables;


        } else return [];

    }

    public function loadManager()
    {

        /* @var $event SmetaEvents */

        if ($estimate_ids = $this->getEstimatesId()) {
            $active_stages = EstimateStage::find()->select('stage_id')->where(['in', 'estimate_id', $estimate_ids])->andWhere(['status' => EstimateStage::STATUS_ACTIVE])->column();
        };
        // D::dump($estimate_ids);
        if ($input = Input::find()->where(['in', 'stage_id', $active_stages])->andWhere(['type' => Input::IN_LIST_OF_MANAGERS])->one()) {
            //  D::dump($input->input_id);
            if ($inputValueStation = InputValue::find()->where(['input_id' => $input->input_id])->andWhere(['smeta_id' => $this->smeta_id])->one()) {
                $station_id = $inputValueStation->value;
                //   D::success($station_id);
            }
            if ($station = User::find()->where(['id' => $station_id])->select('name,phone,email')->asArray()->one()) {
                foreach ($station as $key => $value) {
                    if (!filter_var($value, FILTER_VALIDATE_FLOAT)) $value = "'" . $value . "'";
                    elseif (!$value) $value = 0;
                    $variables["manager." . $key] = $value;
                }
            }
            if ($station) Yii::$app->session->set('manager', $station);
            //   D::dump($station);

            return $variables;


        } else return [];
    }

    public function calcutale()
    {

        /* @var $estimate Estimate */
        /* @var $output Output */

        $variables = $this->loadVariables();
        if ($estimates = $this->estimates) {
            foreach ($estimates as $estimate) {
                D::success(" ESTIMATE  NAME = $estimate->name");

                // D::dump($inputsData);

                if ($stages = $estimate->stagesOutput) {
                    foreach ($stages as $stage) {
                        if ($outputs = $stage->outputs) {
                            D::alert("COUNT OUTPUTS = " . count($outputs));
                            foreach ($outputs as $output) {
                                $value = $output->evaluate($variables);
                                //  D::success("FORUMULA=  " . $formula);
                                //  D::success("VALUE =  " . $value);
                                if ($output_value = OutputValue::find()->where(['smeta_id' => $this->smeta_id])->andWhere(['output_id' => $output->output_id])->one()) {
                                } else {
                                    $output_value = new OutputValue(['smeta_id' => $this->smeta_id, 'output_id' => $output->output_id, 'stage_id' => $output->stage_id]);

                                }
                                $output_value->value = strval($value);
                                if (!$output_value->save()) D::dump($output_value->getErrors());


                            }
                        }
                    }

                };
            }
        };
        // D::success(" ESTIMATE_ID_" . $estimate->estimate_id);


        //   D::dump($outputs);
    }

    /**
     * {@inheritdoc}
     */


    public function attributeLabels()
    {
        return [
            'smeta_id' => 'id',
            'user_id' => 'Мастер',
            'estimate_id' => 'Estimate ID',
            'date' => 'Date',
            'estimate.name' => 'Из',
            'name' => 'Название',
        ];
    }

    /**
     * {@inheritdoc}
     * @return SmetaQuery the active query used by this AR class.
     */
    public static function find()
    {
        return new SmetaQuery(get_called_class());
    }
}
