<?php

namespace common\models;

use Yii;

/**
 * This is the model class for table "works".
 *
 * @property int $id
 * @property string $name Наименование
 * @property int $meisure е.и.
 * @property int $cost Стоимость
 * @property int $self_cost Себестоимость
 */
class Works extends \yii\db\ActiveRecord
{

    public static $formulaName = 'work[{id}]';
    public static $formulaParams = ['id', 'name', 'cost','self_cost','meisure'];


    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return 'works';
    }

    public function formName()
    {
        return parent::formName(); // TODO: Change the autogenerated stub
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['name', 'meisure'], 'required'],
            [['meisure', 'cost', 'self_cost'], 'integer'],
            [['name'], 'string', 'max' => 256],
        ];
    }

    public static function mapMeasure()
    {
        return [
            0 => '',
            1 => 'м2',
            2 => 'м.',
            3 => 'м',
            4 => 'лист',
            5 => 'упак.',
            6 => 'шт',
            7 => 'компл.',
            8 => 'м3',
            9 => 'литр',
            10 => 'мешок',
            11 => 'кг',
            12 => 'шт.',
            13 => 'день',
        ];
    }
    public static function preg_match($body = '') {
        if (preg_match_all('/works_(\d+)_/',$body,$matches)) {
            if ($matches[1]) return array_unique($matches[1]);
        }
        return [];
    }


    public function getMeisureText()
    {
        return self::mapMeasure()[$this->meisure];
    }

    public function getFormulaName()
    {
        return preg_replace("/{id}/", $this->id, self::$formulaName);
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'name' => 'Наименование',
            'meisure' => 'е.и.',
            'cost' => 'Стоимость',
            'self_cost' => 'Себестоимость',
        ];
    }
}
