<?php

namespace common\models;

use Yii;

/**
 * This is the model class for table "works".
 *
 * @property int $id
 * @property string $name Наименование
 * @property int $ei е.и.
 * @property int $cost Стоимость
 * @property int $self_cost Себестоимость
 */
class Works extends \yii\db\ActiveRecord
{

    public static $formulaName = 'work_{id}_';
    public static $formulaParams = ['id', 'name', 'cost','self_cost','ei'];

    public static $pattern = '/work_(\d+)_/';


    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return 'works';
    }

    public function beforeSave($insert)
    {
        if (!$this->cost) $this->cost = 0;
        if (!$this->self_cost) $this->self_cost = 0;

        return parent::beforeSave($insert); // TODO: Change the autogenerated stub
    }

    public function formName()
    {
        return parent::formName(); // TODO: Change the autogenerated stub
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['name', 'ei'], 'required'],
            [['name'], 'unique'],
            [['cost', 'self_cost'], 'integer'],
            [['name','ei'], 'string', 'max' => 256],
        ];
    }

    public static function mapMeasure()
    {
        return [
            0 => '',
            1 => 'м2',
            2 => 'м.',
            3 => 'м',
            4 => 'лист',
            5 => 'упак.',
            6 => 'шт',
            7 => 'компл.',
            8 => 'м3',
            9 => 'литр',
            10 => 'мешок',
            11 => 'кг',
            12 => 'шт.',
            13 => 'день',
        ];
    }
    public static function preg_match($body = '') {
        if (preg_match_all('/work_(\d+)_/',$body,$matches)) {
            if ($matches[1]) return array_unique($matches[1]);
        }
        return [];
    }


    public function getFormulaName()
    {
        return preg_replace("/{id}/", $this->id, self::$formulaName);
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'name' => 'Наименование',
            'ei' => 'е.и.',
            'cost' => 'Стоимость',
            'self_cost' => 'Себестоимость',
        ];
    }
}
