<?php
/**
 * Created by PhpStorm.
 * User: Анастсия
 * Date: 02.12.2018
 * Time: 10:29
 */

namespace console\controllers;

use common\models\Table;
use common\models\TableCells;
use common\models\TableHistory;
use Yii;
use backend\utils\D;
use common\models\Evaluator;

class ConsoleController extends \yii\console\Controller
{

    public function beforeAction($action)
    {
        \backend\utils\D::$isConsole = true;
        return parent::beforeAction($action); // TODO: Change the autogenerated stub
    }

    public function actionToggleClasses()
    {

        $cell = \common\models\TableCells::findOne(45);
        $cell->toggleClass('text-color-red');
        // $cell->toggleClass('text-color-red');
        $cell->toggleClass('text-center');
        $cell->toggleClass('text-9center');
        D::success($cell->classes);
    }

    public function actionTestInversion()
    {
        if ((1) && (1)) echo "TRUE";
        $result = Evaluator::makeBoolean('(1) && (1)');
        D::dump("VALUE = " . $result['value']);
        D::dump($result['type']);
        //  D::dump(eval("!1"));
    }

    public function actionLogDatabase()
    {
        $timestart = time();
        foreach (range(1, 10) as $step) {

            TableHistory::storeNew();

            sleep(2);

        }

        TableHistory::ClearOld();


        D::success("SCRIPTS TAKES " . (time() - $timestart - 20) . " WITH RESPONSE ");


    }

    public function actionRestore()
    {
        $tableHistory = TableHistory::findOne(26);
       // TableHistory::storeNew();
        $tableHistory->restore();
    }

    public function actionGenerateAddresses()
    {
        foreach (TableCells::find()->All() as $cell) {
            $cell->address = $address = $cell->generateAddress();

            D::success(" ADDRESS FOR ".$cell->tr_id." ".$cell->td_id." = ".$cell->address);
            if (!$cell->save()) D::dump($cell->errors);

        }
    }

}