<?php
/**
 * Created by PhpStorm.
 * User: Анастсия
 * Date: 02.12.2018
 * Time: 10:29
 */

namespace console\controllers;

use Yii;
use backend\utils\D;
use common\models\Evaluator;

class ConsoleController extends \yii\console\Controller
{

    public function beforeAction($action)
    {
        \backend\utils\D::$isConsole = true;
        return parent::beforeAction($action); // TODO: Change the autogenerated stub
    }

    public function actionToggleClasses()
    {

        $cell = \common\models\TableCells::findOne(45);
        $cell->toggleClass('text-color-red');
        // $cell->toggleClass('text-color-red');
        $cell->toggleClass('text-center');
        $cell->toggleClass('text-9center');
        D::success($cell->classes);
    }

    public function actionTestInversion()
    {
        if ((1) && (1)) echo "TRUE";
        $result = Evaluator::makeBoolean('(1) && (1)');
        D::dump("VALUE = " . $result['value']);
        D::dump($result['type']);
        //  D::dump(eval("!1"));
    }

    public function actionLogDatabase()
    {
        $timestart = time();
        foreach (range(1, 1) as $item) {
          //  Yii::$app->db->createCommand('')->execute();
            Yii::$app->db->createCommand('DROP TABLE  IF EXISTS `table_cells_history_3`; RENAME TABLE `table_cells_history_2` TO `table_cells_history_3`;
RENAME TABLE `table_cells_history_1` TO `table_cells_history_2`;
CREATE TABLE  `table_cells_history_1` LIKE `table_cells`;
INSERT `table_cells_history_1` SELECT * FROM  `table_cells`;')->execute();
            // Yii::$app->db->createCommand('RENAME TABLE `table_cells_history_2` TO `table_cells_history_3`;')->execute();
            //  Yii::$app->db->createCommand('RENAME TABLE `table_cells_history_1` TO `table_cells_history_2`;')->execute();
            // Yii::$app->db->createCommand('CREATE TABLE  `table_cells_history_1` LIKE `table_cells`')->execute();
            //  Yii::$app->db->createCommand('INSERT `table_cells_history_1` SELECT * FROM  `table_cells`;')->execute();

            Yii::$app->db->createCommand('DROP TABLE  `table_columns_history_3`;')->execute();
            Yii::$app->db->createCommand('RENAME TABLE `table_columns_history_2` TO `table_columns_history_3`;')->execute();
            Yii::$app->db->createCommand('RENAME TABLE `table_columns_history_1` TO `table_columns_history_2`;')->execute();
            Yii::$app->db->createCommand('CREATE TABLE  `table_columns_history_1` LIKE `table_columns`')->execute();
            Yii::$app->db->createCommand('INSERT `table_columns_history_1` SELECT * FROM  `table_columns`;')->execute();

            Yii::$app->db->createCommand('DROP TABLE  `table_rows_history_3`;')->execute();
            Yii::$app->db->createCommand('RENAME TABLE `table_rows_history_2` TO `table_rows_history_3`;')->execute();
            Yii::$app->db->createCommand('RENAME TABLE `table_rows_history_1` TO `table_rows_history_2`;')->execute();
            Yii::$app->db->createCommand('CREATE TABLE  `table_rows_history_1` LIKE `table_rows`')->execute();
            Yii::$app->db->createCommand('INSERT `table_rows_history_1` SELECT * FROM  `table_rows`;')->execute();
        }
        D::success("SCRIPTS TAKES " . (time() - $timestart));


    }

}